services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: MAIN_LISTENER://kafka:9092,CONTROLLER://localhost:9093,OUTSIDE_LISTENER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: MAIN_LISTENER://kafka:9092,OUTSIDE_LISTENER://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: MAIN_LISTENER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,MAIN_LISTENER:PLAINTEXT,OUTSIDE_LISTENER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  flinkjobmanager:
    build: flink_processing
    container_name: job_manager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES= 
        jobmanager.rpc.address: flinkjobmanager
        parallelism.default: 2
    command: jobmanager
  flink_task_manager:
    build: flink_processing
    environment:
      - |
        FLINK_PROPERTIES= 
        jobmanager.rpc.address: flinkjobmanager
        parallelism.default: 2
    deploy:
      replicas: 3
    depends_on:
      - flinkjobmanager
    command: taskmanager
  flink_process:
    build: events_processing
    container_name: flink_process
    environment:
      - |
        FLINK_PROPERTIES= 
        jobmanager.rpc.address: flinkjobmanager
        parallelism.default: 2
    depends_on:
      - flinkjobmanager
    command: ["./bin/flink","run", "--jobmanager", "flinkjobmanager:8081", "--python", "event-processing.py"]

  events_logger:
    build: events_generation
    container_name: events_logger
    command: ["python", "./generate_ecommerce_events.py"]
    volumes:
      - ./.secrets.toml:/usr/src/app/.secrets.toml
    depends_on:
      - kafka
